#!/bin/bash

LOG=/var/log/lsyncd.log

if [ -z "$(pgrep -a 'lsyncd')" ]; then
	echo -e " off \n\n#ff0000"
	exit 33
fi

LAST_SUCCESS=$(grep "Finished a list" $LOG 2> /dev/null | tail -n 1 | cut -d" " -f1-5)
[ -z "$LAST_SUCCESS" ] && echo -e " ? \n\n#ff0000" && exit 33

SECONDS=$(( $(date +%s) - $(date +%s -d "$LAST_SUCCESS") ))
[ $SECONDS -lt   600 ] && exit

[ $SECONDS -gt 86400 ] && echo " $(( $SECONDS / 86400 ))d "   && exit 33
[ $SECONDS -gt  3600 ] && echo " $(( $SECONDS /  3600 ))h "   && exit 33
[ $SECONDS -gt    60 ] && echo " $(( $SECONDS /    60 ))min " && exit 33


