#!/bin/bash

complement() {
	if [ "$(iwgetid | cut -d' ' -f1)" = "$1" ]; then
		echo " ($(iwgetid -r))"
	else
		SPEED="$(cat /sys/class/net/$1/speed 2> /dev/null)"
		GIGABIT=$(($SPEED/1000))

		#echo -e "\n\n$MEGABIT | $GIGABIT\n\n"
		if [ "$SPEED" ]; then
			echo -n " ("
			[ $GIGABIT -gt 0 ] && echo -n "${GIGABIT}G" || echo -n "${SPEED}M"
			echo -n ")"
		fi
	fi
}

FULL_TEXT=
SHORT_TEXT=
COLOR=

OLDIFS=$IFS
IFS=$'\n'
for IF in $(ip -o -4 a); do
	NAME=$(echo $IF | awk '{ print $2 }')
	IP_F=$(echo $IF | awk '{ print $4 }')
	IP_S=$(echo $IP_F | cut -d/ -f1)

	case $NAME in
		lo|virbr*|docker*) continue ;;
		em*)         ICON= ;; # ethernet
		enp0s26u1u2) ICON= ;; # usb
		tun*)        ICON= ;; # tunnel
		wlp3s0)      ICON= ;; # wireless
		*)           ICON= ;; # others
	esac
	FULL_TEXT+="$IP_F$(complement $NAME)   "
	SHORT_TEXT+="$IP_S   "
done
IFS=$OLDIFS

if [ -z "$(echo $FULL_TEXT | xargs)" ]; then
   #echo "no networks"
   #exit 33
   echo ""
fi

echo "$FULL_TEXT" | sed 's/^ *//; s/ *$//'
echo "$SHORT_TEXT" | sed 's/^ *//; s/ *$//'
echo "$COLOR"
